# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Achyudh's Blog
paginate:       5
baseurl:        ""
url:            http://achyudh.github.io/blog

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Achyudh Ram
  url:          http://achyudh.github.io
  email:        achyudhk@live.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/achyudh/blog

# Gems
plugins:
  - jekyll-paginate
